  CREATE TABLE "CUSTOMER" 
   (	"CUSTOMER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CUSTOMER_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	 CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID"), 
	 CONSTRAINT "CONST_CUSTOMER_NO" UNIQUE ("CUSTOMER_NO")
   )
   
  CREATE TABLE "CUSTOMER1" 
   (	"CUSTOMER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CUSTOMER_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	 CONSTRAINT "CUSTOMER1_PK" PRIMARY KEY ("CUSTOMER_ID"),
	 CONSTRAINT "CONST_CUSTOMER1_CUSTOMER_NO" UNIQUE ("CUSTOMER_NO")
   )
   
  CREATE TABLE "CUSTADDRESS" 
   (	"ADDRESS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ADDRESS_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STREET_NO" VARCHAR2(20 BYTE), 
	"STREET" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"ZIP" VARCHAR2(20 BYTE), 
	"CUSTOMER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADDRESS_ID"), 
	 CONSTRAINT "CUSTADDRESS_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("CUSTOMER_ID") ENABLE
   )
   
  CREATE TABLE "CUSTADDRESS1" 
   (	"ADDRESS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ADDRESS_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STREET_NO" VARCHAR2(20 BYTE), 
	"STREET" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"ZIP" VARCHAR2(20 BYTE), 
	"CUSTOMER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "CUSTADDRESS1_PK" PRIMARY KEY ("ADDRESS_ID"), 
	 CONSTRAINT "CUSTADDRESS1_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER1" ("CUSTOMER_ID") ENABLE
   )

  CREATE TABLE "CUSTPHONE" 
   (	"PHONE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PHONE_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"CUSTOMER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "CUSTPHONE_PK" PRIMARY KEY ("PHONE_ID"),
	 CONSTRAINT "CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
     REFERENCES "CUSTOMER" ("CUSTOMER_ID") ENABLE
   )

  CREATE TABLE "CUSTPHONE1" 
   (	"PHONE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PHONE_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"CUSTOMER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "CUSTPHONE1_PK" PRIMARY KEY ("PHONE_ID"), 
	 CONSTRAINT "CUSTOMER1_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER1" ("CUSTOMER_ID") ENABLE
   )
   
CREATE SEQUENCE "CUSTADDRESS1SEQ";
CREATE SEQUENCE "CUSTADDRESSSEQ";
CREATE SEQUENCE "CUSTOMER1SEQ";
CREATE SEQUENCE "CUSTOMERSEQ";
CREATE SEQUENCE "CUSTPHONE1SEQ";
CREATE SEQUENCE "CUSTPHONESEQ";

DECLARE
    CUSTOMER_ID PLS_INTEGER;
    address_id PLS_INTEGER;
    PHONE_ID PLS_INTEGER;
BEGIN
    CUSTOMER_ID := CUSTOMERSEQ.NEXTVAL;
    ADDRESS_ID := CUSTADDRESSSEQ.NEXTVAL;
    PHONE_ID := CUSTPHONESEQ.NEXTVAL;

    insert into customer values (CUSTOMER_ID, 'JY', 'Jun', 'Yan');
    INSERT INTO custphone values (PHONE_ID, 'Home', '5046413682', CUSTOMER_ID);
    INSERT INTO custaddress values (ADDRESS_ID, 'Home', '4H', 'Sierra Cir', 'Owings Mills', 'MD', '21117', CUSTOMER_ID);
END;

    INSERT INTO custphone values (CUSTPHONESEQ.NEXTVAL, 'Work', '6157103564', 1);
    INSERT INTO custaddress values (CUSTADDRESSSEQ.NEXTVAL, 'Home', '4H', 'Sierra Cir', 'Owings Mills', 'MD', '21117', 25);
    INSERT INTO custaddress values (CUSTADDRESSSEQ.NEXTVAL, 'Mailing', '6025', 'Stage Rd', 'Memphis', 'TN', '38134', );
